apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-blue
  labels:
    type: backend-app
    deployment: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      type: backend-app
      deployment: blue
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        type: backend-app
        deployment: blue
    spec:
      containers:
        - name: backend-api-blue
          image: petlog/backend:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /config
          envFrom:
            - configMapRef:
                name: time-zone-config
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms512m -Xmx2048m"
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "3072Mi"
      volumes:
        - name: config-volume
          configMap:
            name: backend-api-config
