apiVersion: v1
kind: Service
metadata:
  name: backend-service   # Ingress와 일치하도록 수정
  namespace: default      # 필요 시 명시
spec:
  selector:
    type: backend-app
    deployment: blue
  ports:
    - protocol: TCP
      port: 8080           # Ingress에서 사용하는 포트
      targetPort: 8080     # 컨테이너 내부 포트
  type: ClusterIP